language: scala
scala: 2.11.12
sudo: required
dist: trusty

services:
  - docker
  - mongodb

addons:
  hosts:
    - localdocker

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt



before_install:
  - docker-compose -f "experiments/Shared/kafka-docker/docker-compose-travis.yml" up -d
  - docker ps -a
matrix:
  include:
    - env: SCALA_VERSION=2.11.12
      os: linux
      jdk: openjdk8


before_script:
  - sleep 10

script:
  - sbt package
  - sbt 'set parallelExecution in ThisBuild := false' "project flinkintegration" test
  - sbt "project flinkintegration" scalafmt::test

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: epochalignment