language: scala
scala: 2.12.2

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers

matrix:
  include:
    - env: SCALA_VERSION=2.12.2
      os: linux
      jdk: oraclejdk8

script:
  - sbt "scalafmt --diff --test"
  - sbt test