language: scala
scala: 2.11.11
sudo: required
dist: trusty

services:
  - docker
  - mongodb


before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt


before_install:
  - docker build -t codefeedr/kafka containers/kafka/
  - docker network create --subnet=192.168.99.0/24 kafkanet
  - docker run --net kafkanet --ip 192.168.99.100 -p 2181:2181 -p 9092:9092 --name kafka --rm --env ADVERTISED_HOST=192.168.99.100 --env ADVERTISED_PORT=9092 --env DELETE_TOPICS=true -d codefeedr/kafka
  - docker ps -a
matrix:
  include:
    - env: SCALA_VERSION=2.11.11
      os: linux
      jdk: oraclejdk8

before_script:
  - sleep 10

script:
  - sbt package
  - sbt 'set parallelExecution in ThisBuild := false' test
  - sbt scalafmt::test