language: scala
scala: 2.11.11
sudo: false

services:
  - mongodb

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt


matrix:
  include:
    - env: SCALA_VERSION=2.11.11
      os: linux
      jdk: oraclejdk8

before_script:
  - sleep 10

script:
  - ./setuptravis.sh
  - sbt test:scalafmt::test
  - sbt test
